/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        sm: '360px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      colors: {
        primary: '#FF094E',
        secondary: '#F5444E',
        text: '#000000',
        darkStorke1: '#fed1d5ff',
        darkStorke: '#FF0A4E',
        greenbg: '#d3feefff',
        lightColor: '#FFFFFF',
        borders: '#FF93A0',
        pink500: '#EC4899',
        white: '#FFFFFF',
        toastbackground: '#FEC7EC',
        toasbgcolor: "#2F2E2E",
        tosaticonbg: "#D9D9D9",
        backgroundColor: '#FFFFFF',
        invisibleText: '#989898',
        yellow: '#f8ee28ff',
        activeText: '#FF094E',
        inactiveText: '#000000',
        gradientColor100: '#F5444E',
        gradientColor0: '#FF094E',
        blue500: '#3B82F6',
        black: '#000000',
        green500: '#10B981',
        red500: '#EF4444',

        alertDangerBackground: '#ffe6e6',
        alertDangerOuterCircle: '#ff4d4d',
        alertDangerTitle: '#b30000',
        alertDangerMessage: '#660000',
        alertWarningBackground: '#fff4e5',
        alertWarningOuterCircle: '#ffb84d',
        alertWarningTitle: '#994d00',
        alertWarningMessage: '#663300',
        alertSuccessBackground: '#e6ffea',
        alertSuccessOuterCircle: '#33cc33',
        alertSuccessTitle: '#237023',
        alertSuccessMessage: '#154715',
        alertInformationBackground: '#e6f0ff',
        alertInformationOuterCircle: '#4d79ff',
        alertInformationTitle: '#0033cc',
        alertInformationMessage: '#001a66',
      },
      fontFamily: {
        extrabold: 'FunnelDisplay-ExtraBold',
        bold: 'FunnelDisplay-Bold',
        semibold: 'FunnelDisplay-SemiBold',
        medium: 'FunnelDisplay-Medium',
        regular: 'FunnelDisplay-Regular',
        light: 'FunnelDisplay-Light',
        shadowsRegular: 'ShadowsIntoLight-Regular',
        shadowsNormal: 'ShadowsIntoLight-normal',
      },
      fontSize: {
        'betsie-logo': '62.85px',
      },
      letterSpacing: {
        'betsie-logo': '0.08em',
      },
    },
  },
  plugins: [],
};
